# -*- coding: utf-8 -*-
"""Bayers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHdUYKks1JbkaNGoG1PdcQdU8uQ9GEOm
"""

priors = {
    "H1" : 1/3,
    "H2" : 1/3,
    "H3" : 1/3
}

likeihoods = {
    "H1" : 1/2,
    "H2" : 0.0,
    "H3" : 1.0,
}

p_e = sum(likeihoods[h] * priors[h] for h in priors)
posteriors = {h: (likeihoods[h] * priors[h] / p_e for h in priors)}

p_e, posteriors

import random
from collections import Counter

def host_opens(player_choice, car_door):
  doors = [1,2,3]
  options = [d for d in doors if d != player_choice and d != car_door]
  return random.choice(options)

N = 2000000
count_event = 0
wins_stay_given_event = 0
wins_switch_giver_event = 0
cars_given_event = Counter()

for _ in range (N):
  car = random.choice([1,2,3])
  player = 1
  opened = host_opens(player, car)

  if opened == 2:
    count_event += 1
    cars_given_event[car] += 1

    if car == 1:
      wins_stay_given_event += 1
    ramaining_closed = [d for d in [1,2,3] if d not in (player, opened)][0]
    if remaining_closed == car:
      wins_switch__given_event += 1

{
    'P(H1)'
}