# -*- coding: utf-8 -*-
"""Continuas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ox2doDDaFLCCdVwmEcBwOy8BF-9buX7l
"""

Distribuição delta

from scipy.stats import gamma
import pandas as pd
import statsmodels.api as sm
import numpy as np
from scipy import stats
import warnings
warnings.filterwarnings("ignore")

alpha = 2
theta = 5
x = 20

prob_maior_20 = gamma.sf(x, a=alpha, loc=0, scale=theta)

print(prob_maior_20)

dataFrame = pd.read_csv("dataset_correlacao.csv")
dataFrame.head()

stats.kstest(dataFrame['Pontos'], 'norm')

statistic, pvalue = stats.kstest(dataFrame['Pontos'], 'norm')

if pvalue > 0.29407:
  print("Não é distribuição normal")
else:
  print("É distribuição normal")

print(stats.shapiro(dataFrame['Pontos']))

if stats.shapiro(dataFrame['Pontos'])[1] > 0.05:
  print("Não é distribuição normal")
else:
  print("É distribuição normal")

dataFrame = pd.read_csv("premier_league.csv")
dataFrame.head()

print(stats.shapiro(dataFrame['pts']))

dataFrame['pts'][dataFrame['pts'] > 105.58] = 105.58
dataFrame['pts'][dataFrame['pts'] < 48.62] = 48.62

print(stats.shapiro(dataFrame['pts']))

#BOX COX
pontos_novo, lambda_box = stats.boxcox(dataFrame['pts'])

print(stats.shapiro(pontos_novo))

dataFrame.head()

from scipy.special import inv_boxcox
pontos_velho = inv_boxcox(pontos_novo, lambda_box)
pontos_velho