# -*- coding: utf-8 -*-
"""Distribuicao_discreta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5eZA8hPo9QdhcINFrDUsIwOyTUlx921
"""

from scipy.stats import binom, geom, nbinom, hypergeom, poisson

n = 100
p = 0.7
k = 80

prob = binom.pmf(k,n,p)
print(f"P(X = {k}) = {prob:.4f}")

"""Geométrica

"""

p = 0.05
k = 4

probabilidade = geom.pmf(k,p)

print(f'Probabilidade de a primeira venda acontecer na {k}ª ligação: {probabilidade:.6f}')
print(f'Em porcentagem: {probabilidade * 100:.2f}%')

"""Pascal"""

r = 3
p = 0.05
k = 50

x = k - r

probabilidade = nbinom.pmf(x, r, p)

print(f'Probabilidade de a {r}ª venda acontecer na {k}ª ligação: {probabilidade:.6f}')
print(f'Em porcentagem: {probabilidade * 100:.2f}%')

"""Hipergeométrica"""

N = 1000
k = 50
n = 50
k = 3

probabilidade = hypergeom.pmf(k,N,K,n)

print(f'Probabilidade de exatamente {k} sucessos na amostra: {probabilidade:.6f}')
print(f'Em porcentagem: {probabilidade * 100:4f}%')