# -*- coding: utf-8 -*-
"""EstatisticaAplicada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111l7PcdyytjJXmgR9ofYTe2VB0mB6yjq
"""

import numpy as np
from scipy import stats

conjuntoDados = np.array([30,32,32,36,39,43,46,48,49,50,52,53,56,57,63,65,74,75,90])
mediaConjuntoDadosUm = 0
soma = 0

for i in range(len(conjuntoDados)):
  soma += conjuntoDados[i]

mediaConjuntoDadosUm = soma/len(conjuntoDados)

print('O resultado da primeira forma de calcular a média é: ', mediaConjuntoDadosUm)

#MEDIANA
print("O resultado da forma de calcula a mediana é: ", np.median(conjuntoDados))

#MODA
print("O resultado da forma de calcular a moda é: ", stats.mode(conjuntoDados))

#AMPLITUDE
print(f"O resultado da forma de calcular a amplitude é: {conjuntoDados.max() - conjuntoDados.min()}")

#QUARTIL

#Q1
print(f"O resultado da forma de calcula Q1 é: {np.percentile(conjuntoDados, 25)}")

#Q2
print(f"O resultado da forma de calcula Q2 é: {np.percentile(conjuntoDados, 50)}")

#Q3
print(f"O resultado da forma de calcula Q3 é: {np.percentile(conjuntoDados, 75)}")

#FORMAS DE CALCULAR DESVIO PADRÃO

#FORMA 1 - NA UNHA

desvioPadrao = varianca ** 0.5
print(f"O resultado da primeira forma de calcular o desvio padrão é: ", desvioPadrao)

#FORMA 2 - Com a biblioteca Numpy
desvioPadrao = np.std(conjuntoDados)
print(f"O resultado da segunda forma de calcular o desvio padrão é: ", desvioPadrao)

listaDois = np.array([183.8,125.4,193.3,162,142.3,140.6,456.8,228.7,231.4,86.1,199.6,235.3,218.6,128,125.4,244.2,147.8,118.2,347.5,150.1,236.9,214.6,214.1,257.3,362.8,140.7,113.8])

#MEDIA
media = sum(listaDois)/len(listaDois)
print(f"A média é: {media}")

#Q1
print(f"Q1: {np.percentile(conjuntoDados, 25)}")

#Q2
print(f"Q2: {np.percentile(listaDois, 50)}")

#Q3
print(f"Q3 {np.percentile(listaDois, 75)}")

#VARIAÇA
varianca = np.var(listaDois)
print(f"A variança é {varianca}")

#DEVIO PADRÃO

desvioPadrao = np.std(listaDois)
print(f"Desvio padrão: {desvioPadrao}")

#BoxSpot

from matplotlib import pyplot
pyplot.boxplot(listaDois)

"""Correlação  """

import pandas as pd
import matplotlib.pyplot as plt

arrayCalcular = [
    [1, 86],
    [2, 60],
    [3, 61],
    [4, 64],
    [5, 51],
    [6, 39],
    [7, 44],
    [8, 42],
    [9, 50],
    [10, 46],
    [11, 44],
    [12, 39],
    [13, 44],
    [14, 38],
    [15, 31],
    [16, 36],
    [17, 27],
    [18, 24],
    [19, 31],
    [20, 18],
]

dataFramerCalcular = pd.DataFrame(arrayCalcular, columns= ['Posição', 'Gols'])
dataFramerCalcular.head()

dataFramerCalcular.corr()

plt.scatter(dataFramerCalcular['Gols'], dataFramerCalcular['Posição'])
plt.title("Correlação")