# -*- coding: utf-8 -*-
"""Estimativas_VariedadeAmostral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Brk5eO5V6P7cUIp_0Z-ieVSunASVpceC
"""

z = 0.95
p = 0.5
E = 0.05
N = 2000


def calcula_estimativa(z, p, E):
  return ((z**2) * (p * (1 - p)))/(E**2)

n = calcula_estimativa(z, p, E)

print(f'O resultado não normalizado: {n}')

def calcula_suavizacao(n, N):
  if((n/N) > 0.05):
    return n / (1 + ((n - 1) / N))
  return n

n_normalizado = calcula_suavizacao(n, N)

print(f'O resultado normalizado é: {n_normalizado}')

"""Variedade amostral"""

dados = [2,3,4,5,5,7,5,3,6,7,8]

def estimador_proporcao(dados_binarios):
  return sum(dados_binarios) / len(dados_binarios)

def estimador_media(dados):
  return sum(dados) / len(dados)

def estimador_variancia(dados):
  media = estimador_media(dados)
  soma = sum((x - media) ** 2 for x in dados)
  return soma / (len(dados) - 1)


variancia = estimador_variancia(dados)

print(f'A variancia é : {variancia}')