# -*- coding: utf-8 -*-
"""intervalo_de_confianca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbU42bCoASCXHhCMMJMjH73t7EdNX-pH

Intervalo de confiança
"""

import math
from scipy.stats import norm, t

def intervalo_confianca_media(media_amostral, desvio_amostral, n, confianca=0.95, populacao_finita=False, N=None):

  if n <= 1:
    raise ValueError("n Deve ser maior que 1.")
  if desvio_amostral < 0:
    raise ValueError("O desvio-padrão amostral não pode ser negativo")
  if not (0 < confianca < 1):
    raise ValueError("A confiança deve estar entre 0 e 1. Ex: 0.95")

  alpha = 1 - confianca
  gl = n - 1

  if n < 30:
    metodo = 't de Student'
    valor_critico = t.ppf(1 - alpha / 2, df=gl)
  else:
    metodo = 'normal (z)'
    valor_critico = norm.ppf(1 - alpha / 2)

  erro_padrao = desvio_amostral / math.sqrt(n)
  fpc = 1.0

  if populacao_finita:
    if N is None:
      raise ValueError("Informe N quando a população for finita")
    if N <= 1:
      raise ValueError("N deve ser maior que 1")
    if n > N:
      raise ValueError("n não pode ser maior que N")

    fpc = math.sqrt((N - n) / (N - 1)) if N > 1 else 1.0
    erro_padrao *= fpc

    margem_erro = valor_critico * erro_padrao
    li = media_amostral - margem_erro
    ls = media_amostral + margem_erro

    return {
        'metodo' : metodo,
        'graus_de_liberdade': gl,
        'valor_critico': valor_critico,
        'erro_padrao': erro_padrao,
        'fator_correcao_pop_finita': fpc,
        'margem_erro': margem_erro,
        'limite_inferior': li,
        'limite_superior': ls
    }

"""Com poucas amostras e tabela normal *"""

resultado1 = intervalo_confianca_media(
    media_amostral=8.4,
    desvio_amostral=2.0,
    n=25,
    confianca=0.99
)

print('Exemplo 1 - População pequena')

print(f"Metodo usado: {resultado1['metodo']}")
print(f"Graus de Liberdade: {resultado1['graus_de_liberdade']}")
print(f"Valor crítico: {resultado1['valor_critico']:.3f}")
print(f"Erro padrão: {resultado1['erro_padrao']:.3f}")
print(f"Margem de erro: {resultado1['margem_erro']:.3f}")
print(f"IC: {resultado1['limite_inferior']:.3f}")
print(f"LS: {resultado1['limite_superior']:.3f}")

resultado1 = intervalo_confianca_media(
    media_amostral=8.4,
    desvio_amostral=2.0,
    n=25,
    confianca=0.99,
    populacao_finita=True,
    N = 250
)

print('Exemplo 2 - População maior')

print(f"Metodo usado: {resultado1['metodo']}")
print(f"Graus de Liberdade: {resultado1['graus_de_liberdade']}")
print(f"Valor crítico: {resultado1['valor_critico']:.3f}")
print(f"Erro padrão: {resultado1['erro_padrao']:.3f}")
print(f"Margem de erro: {resultado1['margem_erro']:.3f}")
print(f"IC: {resultado1['limite_inferior']:.3f}")
print(f"LS: {resultado1['limite_superior']:.3f}")