# -*- coding: utf-8 -*-
"""Regressao_linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBVHO8AZ1ubqarhi8qPksjotB5zcoYph
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import statsmodels.api as sm

tempo_escola = np.array([15,20,20,40,50,25,10,55,35,30])
distancia = np.array([8,6,15,20,25, 11,5,32,28,20])

plt.scatter(tempo_escola, distancia)
plg_title("Gráfico de dispersão")
plt.show()

distancia_constante = sm.add_constant(distancia)
resultado = sm.OLS(tempo_escola, distancia_constante).fit()

print(resultado.summary())

tempo_escola = np.array([15,20,20,40,50,25,10,55,35,30])
distancia = np.array([8,6,15,20,25, 11,5,32,28,20])
semaforos = np.array([0,1,0,1,2,1,0,3,1,1])

#JUNTAR AS VARIAÁVEIS EXPLICATIVAS

explicativas = np.column_stack((distancia, semaforos))
explicativas_constante = sm.add_constant(explicativas)

resultado_novo = sm.OLS(tempo_escola, explicativas_constante).fit()
print(resultado_novo.summary())

"""Agora, com get dummy"""

tempo_escola = np.array([15,20,20,40,50,25,10,55,35,30])
distancia = np.array([8,6,15,20,25, 11,5,32,28,20])
semaforos = np.array([0,1,0,1,2,1,0,3,1,1])
periodo = np.array([1,1,1,0,0,1,1,0,1,1])

#JUNTAR AS VARIAÁVEIS EXPLICATIVAS

explicativas = np.column_stack((distancia, semaforos, periodo))
explicativas_constante = sm.add_constant(explicativas)

resultado_novo = sm.OLS(tempo_escola, explicativas_constante).fit()
print(resultado_novo.summary())

"""Adicionando estilo de pilotagem"""

tempo_escola = np.array([15,20,20,40,50,25,10,55,35,30])
distancia = np.array([8,6,15,20,25, 11,5,32,28,20])
semaforos = np.array([0,1,0,1,2,1,0,3,1,1])
periodo = np.array([1,1,1,0,0,1,1,0,1,1])
estilo_1 = np.array([0,1,1,0,0,1,0,0,1,1])
estilo_2 = np.array([0,0,0,1,1,0,0,0,0,0])

#JUNTAR AS VARIAÁVEIS EXPLICATIVAS

explicativas = np.column_stack((distancia, semaforos, periodo, estilo_1, estilo_2))
explicativas_constante = sm.add_constant(explicativas)

resultado_novo = sm.OLS(tempo_escola, explicativas_constante).fit()
print(resultado_novo.summary())

#PRÓXIMAS OBS

distancia_futuro = np.array([12,30,15])
semaforos_futuro = np.array([2,1,0])
periodo_futuro = np.array([1,0,1])
estilo_1 = np.array([1,1,0])
estilo_2 = np.array([1,0,0])

explicativas_futuras = np.column_stack((distancia_futuro, semaforos_futuro, periodo_futuro, estilo_1, estilo_2))

explicativas_futuras = sm.add_constant(explicativas_futuras)
resultado_novo.predict(explicativas_futuras)

"""Exercício tal"""

calorias_gastas = np.array([274.5, 160, 368, 267, 640, 356, 396.5, 213.5, 178, 164.7])
tempo_minutos = np.array([45, 10, 23, 30, 40, 40, 65, 35, 20, 27])

estilo_1 = np.array([
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    0,
    1
])

estilo_2 = np.array([
    0,
    1,
    1,
    0,
    1,
    0,
    0,
    0,
    0,
    0
])

estilo_3 = np.array([
    0,
    0,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    0
])

#JUNTAR AS VARIAÁVEIS EXPLICATIVAS

explicativas = np.column_stack((tempo_minutos, estilo_1, estilo_2, estilo_3))
explicativas_constante = sm.add_constant(explicativas)

resultado_novo = sm.OLS(calorias_gastas, explicativas_constante).fit()
print(resultado_novo.summary())

# =========================================================
# INSTALAR DEPENDÊNCIAS NO GOOGLE COLAB
# =========================================================

!pip install xgboost joblib -q

# =========================================================
# IMPORTS
# =========================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from xgboost import XGBRegressor

import joblib

# =========================================================
# UPLOAD DO ARQUIVO CSV
# =========================================================

from google.colab import files

uploaded = files.upload()

# =========================================================
# CARREGAR BASE
# =========================================================

# Troque pelo nome exato do arquivo enviado
df = pd.read_csv('base_normalizada_boxcox.csv')

print(df.head())

# =========================================================
# DEFINIR TARGET
# =========================================================

# Para modelos de árvore:
TARGET = 'log_target'

# Para regressão linear:
# TARGET = 'log_target_normalizado'

# =========================================================
# REMOVER COLUNAS DESNECESSÁRIAS
# =========================================================

colunas_remover = [
    'valorPagoEmpenho',
    'log_target',
    'log_target_normalizado',
    'lambda_boxcox'
]

features = [c for c in df.columns if c not in colunas_remover]

X = df[features]
y = df[TARGET]

# =========================================================
# GARANTIR QUE TODAS AS FEATURES SÃO NUMÉRICAS
# =========================================================

# Converte categóricas automaticamente
X = pd.get_dummies(X, drop_first=True)

# Remove infinitos e NaNs
X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna(0)

print(f'\nQuantidade de features: {X.shape[1]}')

# =========================================================
# TREINO / TESTE
# =========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# =========================================================
# MODELO
# =========================================================

modelo = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

# =========================================================
# TREINAR
# =========================================================

print('\nTreinando modelo...')

modelo.fit(X_train, y_train)

print('Treinamento finalizado!')

# =========================================================
# PREDIÇÕES
# =========================================================

pred_log = modelo.predict(X_test)

# =========================================================
# CONVERTER PARA ESCALA REAL
# =========================================================

pred_real = np.exp(pred_log)
y_real = np.exp(y_test)

# =========================================================
# MÉTRICAS
# =========================================================

mae = mean_absolute_error(y_real, pred_real)

rmse = np.sqrt(mean_squared_error(y_real, pred_real))

r2 = r2_score(y_real, pred_real)

print('\n========== RESULTADOS ==========')
print(f'MAE  : {mae:,.2f}')
print(f'RMSE : {rmse:,.2f}')
print(f'R²   : {r2:.4f}')

# =========================================================
# IMPORTÂNCIA DAS FEATURES
# =========================================================

importancias = pd.DataFrame({
    'feature': X.columns,
    'importance': modelo.feature_importances_
})

importancias = importancias.sort_values(
    by='importance',
    ascending=False
)

print('\n========== TOP FEATURES ==========')
print(importancias.head(15))

# =========================================================
# SALVAR MODELO
# =========================================================

joblib.dump(modelo, 'modelo_xgboost.pkl')

print('\nModelo salvo com sucesso!')

# =========================================================
# BAIXAR MODELO
# =========================================================

files.download('modelo_xgboost.pkl')