# -*- coding: utf-8 -*-
"""TrabalhoEstatistica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXQHnp4pfW9odvhPBj6wY6BRbh4loJzJ
"""

import pandas as pd
import json
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

# ============================================================
# CONFIG VISUAL
# ============================================================
plt.rcParams.update({
    'figure.dpi': 150,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'axes.spines.top': False,
    'axes.spines.right': False,
})

# ============================================================
# 1. LEITURA ROBUSTA DOS JSONs
# ============================================================
def carregar_json(caminho: str) -> pd.DataFrame:
    """Lê um arquivo JSON (lista ou objeto) e retorna um DataFrame."""
    for tentativa in [caminho, caminho + '.json']:
        if os.path.exists(tentativa):
            with open(tentativa, 'r', encoding='utf-8') as f:
                conteudo = json.load(f)
            if isinstance(conteudo, list):
                return pd.json_normalize(conteudo)
            elif isinstance(conteudo, dict):
                # Tenta encontrar a lista dentro do dict
                for v in conteudo.values():
                    if isinstance(v, list):
                        return pd.json_normalize(v)
                return pd.json_normalize([conteudo])
    print(f"[AVISO] Arquivo não encontrado: {caminho}")
    return pd.DataFrame()

df_despesas  = carregar_json('/content/Documentos/Execucao_Detalhada_de_Despesas-2026')
df_contratos = carregar_json('/content/Documentos/Relacao_de_Contratos-2026')
df_licitacoes = carregar_json('/content/Documentos/Processos_Licitatorios_Finalizados-2026')

print(f"Despesas:   {df_despesas.shape}  | Colunas: {list(df_despesas.columns[:8])}")
print(f"Contratos:  {df_contratos.shape} | Colunas: {list(df_contratos.columns[:8])}")
print(f"Licitações: {df_licitacoes.shape}| Colunas: {list(df_licitacoes.columns[:8])}")

# ============================================================
# 2. PADRONIZAÇÃO DO NOME DE ENTIDADE (chave de join)
# ============================================================
import unicodedata

def normalizar(nome):
    if pd.isna(nome):
        return "DESCONHECIDO"
    s = str(nome).upper().strip()
    s = unicodedata.normalize('NFKD', s)
    s = ''.join(c for c in s if not unicodedata.combining(c))
    return s

for df in [df_despesas, df_contratos, df_licitacoes]:
    if 'nomeEntidade' in df.columns:
        df['Entidade_Chave'] = df['nomeEntidade'].apply(normalizar)
    else:
        df['Entidade_Chave'] = 'DESCONHECIDO'

# ============================================================
# 3. CONVERSÃO DE TIPOS NUMÉRICOS
# ============================================================
def to_numeric(df, cols):
    for c in cols:
        if c in df.columns:
            df[c] = pd.to_numeric(
                df[c].astype(str).str.replace(',', '.', regex=False).str.replace(r'[^\d.\-]', '', regex=True),
                errors='coerce'
            ).fillna(0)
    return df

df_despesas  = to_numeric(df_despesas,  ['valorEmpenhado', 'valorPagoEmpenho', 'saldoAPagar'])
df_contratos = to_numeric(df_contratos, ['valorFinal', 'valorInicial'])
df_licitacoes = to_numeric(df_licitacoes, ['valorEstimado', 'valorHomologado'])

# ============================================================
# 4. AGRUPAMENTO POR ENTIDADE
# ============================================================
resumo_despesas = df_despesas.groupby('Entidade_Chave', as_index=False).agg(
    Total_Empenhado    =('valorEmpenhado',    'sum'),
    Total_Pago         =('valorPagoEmpenho',  'sum'),
    Saldo_A_Pagar      =('saldoAPagar',       'sum'),
)

resumo_contratos = df_contratos.groupby('Entidade_Chave', as_index=False).agg(
    Qtd_Contratos           =('numero',       'count'),
    Valor_Total_Contratos   =('valorFinal',   'sum'),
    Valor_Inicial_Contratos =('valorInicial', 'sum'),
)

# Participantes: suporta coluna numérica OU lista serializada
if 'participantes' in df_licitacoes.columns:
    df_licitacoes['qtd_part'] = df_licitacoes['participantes'].apply(
        lambda x: len(x) if isinstance(x, list) else (
            int(x) if str(x).isdigit() else 0
        )
    )
elif 'quantidadeParticipantes' in df_licitacoes.columns:
    df_licitacoes['qtd_part'] = pd.to_numeric(df_licitacoes['quantidadeParticipantes'], errors='coerce').fillna(0)
else:
    df_licitacoes['qtd_part'] = 0

id_licit = 'numeroProcesso' if 'numeroProcesso' in df_licitacoes.columns else df_licitacoes.columns[0]

resumo_licitacoes = df_licitacoes.groupby('Entidade_Chave', as_index=False).agg(
    Qtd_Licitacoes              =(id_licit,         'count'),
    Valor_Estimado_Licitacoes   =('valorEstimado',  'sum'),
    Valor_Homologado_Licitacoes =('valorHomologado','sum'),
    Media_Participantes         =('qtd_part',       'mean'),
)

# ============================================================
# 5. MERGE FINAL
# ============================================================
df = pd.merge(resumo_despesas,  resumo_contratos,  on='Entidade_Chave', how='outer')
df = pd.merge(df,               resumo_licitacoes, on='Entidade_Chave', how='outer')
df = df.fillna(0)

df['Ticket_Medio_Contrato'] = df['Valor_Total_Contratos'] / df['Qtd_Contratos'].replace(0, np.nan)
df['Ticket_Medio_Contrato'] = df['Ticket_Medio_Contrato'].fillna(0)

print(f"\n✅ Base final: {df.shape[0]} órgãos × {df.shape[1]} variáveis")
print(df[['Entidade_Chave','Total_Empenhado','Qtd_Contratos','Qtd_Licitacoes']].sort_values('Total_Empenhado', ascending=False).head(10).to_string(index=False))

# ============================================================
# 6. BOXPLOTS INDIVIDUAIS — 1 POR VARIÁVEL (com outliers nomeados)
# ============================================================
VARIAVEIS = [
    ('Total_Empenhado',             'Total Empenhado (R$)'),
    ('Total_Pago',                  'Total Pago (R$)'),
    ('Saldo_A_Pagar',               'Saldo a Pagar (R$)'),
    ('Qtd_Contratos',               'Qtd. de Contratos'),
    ('Valor_Total_Contratos',       'Valor Total dos Contratos (R$)'),
    ('Valor_Inicial_Contratos',     'Valor Inicial dos Contratos (R$)'),
    ('Qtd_Licitacoes',              'Qtd. de Licitações'),
    ('Valor_Estimado_Licitacoes',   'Valor Estimado em Licitações (R$)'),
    ('Valor_Homologado_Licitacoes', 'Valor Homologado (R$)'),
    ('Media_Participantes',         'Média de Participantes por Licitação'),
    ('Ticket_Medio_Contrato',       'Ticket Médio por Contrato (R$)'),
]

def formatar_reais(x, pos=None):
    if x >= 1e6:   return f'R${x/1e6:.1f}M'
    if x >= 1e3:   return f'R${x/1e3:.0f}K'
    return f'R${x:.0f}'

def rotular_outliers(ax, serie, entidades):
    """Anota os outliers extremos com o nome do órgão."""
    q1, q3 = serie.quantile(0.25), serie.quantile(0.75)
    iqr = q3 - q1
    limite_sup = q3 + 1.5 * iqr
    limite_inf = q1 - 1.5 * iqr
    outliers = serie[(serie > limite_sup) | (serie < limite_inf)]
    for idx in outliers.index:
        val = serie[idx]
        label = entidades[idx][:28]  # limita o texto
        ax.annotate(
            label,
            xy=(0, val),
            xytext=(0.55, val),
            fontsize=7,
            color='#c0392b',
            arrowprops=dict(arrowstyle='->', color='#c0392b', lw=0.8),
        )

fig, axes = plt.subplots(4, 3, figsize=(18, 22))
axes = axes.flatten()

for i, (col, titulo) in enumerate(VARIAVEIS):
    ax = axes[i]
    serie = df[col].copy()

    bp = ax.boxplot(
        serie,
        vert=True,
        patch_artist=True,
        widths=0.4,
        boxprops=dict(facecolor='#AED6F1', color='#2C3E50'),
        medianprops=dict(color='#E74C3C', linewidth=2.5),
        whiskerprops=dict(color='#2C3E50', linewidth=1.5),
        capprops=dict(color='#2C3E50', linewidth=1.5),
        flierprops=dict(marker='o', markerfacecolor='#E74C3C', markersize=5, linestyle='none', alpha=0.7),
    )

    # Linha da média
    media = serie.mean()
    ax.axhline(media, color='#27AE60', linestyle='--', linewidth=1.5, label=f'Média: {formatar_reais(media)}')

    # Estatísticas no título
    q1, med, q3 = serie.quantile(0.25), serie.median(), serie.quantile(0.75)
    n_outliers = int(((serie < q1 - 1.5*(q3-q1)) | (serie > q3 + 1.5*(q3-q1))).sum())

    ax.set_title(f'{titulo}\nMediana={formatar_reais(med)} | IQR={formatar_reais(q3-q1)} | Outliers={n_outliers}', fontsize=9)
    ax.set_xticks([])
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(formatar_reais))
    ax.legend(fontsize=7, loc='upper right')

    # Rotula outliers com nome do órgão
    rotular_outliers(ax, serie, df['Entidade_Chave'].values)

# Remove eixo extra
axes[-1].set_visible(False)

plt.suptitle('Boxplots — Distribuição por Órgão/Secretaria\nPrefeitura de Criciúma · 2026', fontsize=16, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('boxplots_cricuma.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Boxplots salvos em boxplots_cricuma.png")

# ============================================================
# 7. HEATMAP DE CORRELAÇÃO
# ============================================================
colunas_corr = [c for c, _ in VARIAVEIS]
corr = df[colunas_corr].corr()

fig, ax = plt.subplots(figsize=(13, 9))
mask = np.zeros_like(corr, dtype=bool)
mask[np.triu_indices_from(mask, k=1)] = True  # mostra triângulo inferior

sns.heatmap(
    corr,
    mask=mask,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    vmin=-1, vmax=1,
    linewidths=0.5,
    annot_kws={'size': 8},
    ax=ax,
    square=True,
)
ax.set_title('Matriz de Correlação — Causa Raiz × Variáveis Influenciadoras\nPrefeitura de Criciúma · 2026', fontsize=14, fontweight='bold')
plt.xticks(rotation=45, ha='right', fontsize=9)
plt.yticks(rotation=0, fontsize=9)
plt.tight_layout()
plt.savefig('correlacao_cricuma.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Heatmap salvo em correlacao_cricuma.png")

# ============================================================
# 8. TOP 10 ÓRGÃOS POR TOTAL EMPENHADO (ranking visual)
# ============================================================
top10 = df.nlargest(10, 'Total_Empenhado')[['Entidade_Chave', 'Total_Empenhado']].copy()
top10['label'] = top10['Total_Empenhado'].apply(lambda x: formatar_reais(x))

fig, ax = plt.subplots(figsize=(12, 6))
bars = ax.barh(top10['Entidade_Chave'][::-1], top10['Total_Empenhado'][::-1], color='#3498DB', edgecolor='white')
for bar, lbl in zip(bars, top10['label'][::-1]):
    ax.text(bar.get_width() * 1.01, bar.get_y() + bar.get_height()/2, lbl, va='center', fontsize=9)
ax.xaxis.set_major_formatter(mticker.FuncFormatter(formatar_reais))
ax.set_title('Top 10 Órgãos por Total Empenhado — Criciúma 2026', fontsize=14, fontweight='bold')
ax.set_xlabel('Total Empenhado (R$)')
plt.tight_layout()
plt.savefig('top10_empenhado.png', bbox_inches='tight', dpi=150)
plt.show()
print("✅ Ranking salvo em top10_empenhado.png")